### ISSUE TITLE
Monument diagram is incorrect

### ISSUE THREAD

**Issue by cbinding** [cbinding/LD4HE#4]
Diagram shows elements of Artefact diagram (oak picture frame) - revise to show a monument..

**Comment by Keith-May** [comment]
What oak picture frame?

**Comment by Keith-May** [comment]
Oh I get it. The model diagram you used for Monument is a cut&paste of the Artefact diagram!

**Comment by cbinding** [comment]
The issue is referring to the current diagram at https://cbinding.github.io/LD4HE/ld4he-monument/

**Comment by cbinding** [comment]
Monument diagram revised to something more sensible
